version: 2.1

orbs:
  python: circleci/python@3.2.0

jobs:
  test:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: custom
          pre-install-steps:
            - run:
                name: Install uv
                command: |
                  curl -LsSf https://astral.sh/uv/install.sh | sh
          install-steps:
            - run:
                name: Install dependencies
                command: |
                  uv pip install -e .
      - run:
          name: Run tests
          command: |
            python -m pytest tests/ -v
workflows:
  main:
    jobs:
      - test
